	*llx = llx_o;
	*llxt = 16;
	*urx = urx_o;
	*urxt = 16;
	*lly = lly_o;
	*llyt = 16;
	*ury = ury_o;
	*uryt = 16;
	strcpy(fname,WuName());
	*fnamet = 3;
	*lst = lst_o;
	*lstt = 16;
	*year = CurrentYear();
	*yeart = 16;
	*latp = latp_o;
	*latpt = 16;
	*hlbt = 3;
	*vlbt = 3;
	*mlbt = 3;
	parse_(&cmnd_.gstr,wut_,wub.c);
	llx_o = *llx;
	urx_o = *urx;
	lly_o = *lly;
	ury_o = *ury;
	lst_o = *lst;
	latp_o = *latp;
