extern Node met_[];
union {
	char c[263];
	short int s[1];
	int l[1];
	double d[1];
} meb;
#define cra (meb.d + 0)
#define cdec (meb.d + 1)
#define rra1 (meb.d + 2)
#define rra2 (meb.d + 3)
#define rdec1 (meb.d + 4)
#define rdec2 (meb.d + 5)
#define cl (meb.d + 6)
#define cb (meb.d + 7)
#define rl1 (meb.d + 8)
#define rl2 (meb.d + 9)
#define rb1 (meb.d + 10)
#define rb2 (meb.d + 11)
#define ffreq1 (meb.d + 12)
#define ffreq2 (meb.d + 13)
#define fwght (meb.d + 14)
#define lbknd (meb.l + 30)
#define fs (meb.l + 31)
#define ps (meb.l + 32)
#define bs (meb.l + 33)
#define bp (meb.l + 34)
#define sk (meb.l + 35)
#define sa (meb.l + 36)
#define se (meb.l + 37)
#define updat (meb.l + 38)
#define pl (meb.l + 39)
#define sn1f (meb.c + 160)
#define sn2f (meb.c + 166)
#define sssf (meb.c + 172)
#define sn1n (meb.s + 82)
#define sn2n (meb.s + 85)
#define sssn (meb.s + 88)
#define ctp (meb.s + 89)
#define ctpfl (meb.s + 90)
#define crat (meb.s + 91)
#define cdect (meb.s + 92)
#define rrat (meb.s + 93)
#define rraf (meb.s + 94)
#define rdect (meb.s + 95)
#define rdecf (meb.s + 96)
#define clt (meb.s + 97)
#define cbt (meb.s + 98)
#define rlt (meb.s + 99)
#define rlf (meb.s + 100)
#define rbt (meb.s + 101)
#define rbf (meb.s + 102)
#define lbetyp (meb.s + 103)
#define befl (meb.s + 104)
#define lbkndt (meb.s + 105)
#define ffreqt (meb.s + 106)
#define fwghtt (meb.s + 107)
#define fst (meb.s + 108)
#define pst (meb.s + 109)
#define bst (meb.s + 110)
#define bpt (meb.s + 111)
#define skt (meb.s + 112)
#define sat (meb.s + 113)
#define set (meb.s + 114)
#define smact (meb.s + 115)
#define rmact (meb.s + 116)
#define emact (meb.s + 117)
#define snt (meb.s + 118)
#define snf (meb.s + 119)
#define ssst (meb.s + 120)
#define sssfl (meb.s + 121)
#define updatt (meb.s + 122)
#define plt (meb.s + 123)
#define smac (meb.c + 248)
#define rmac (meb.c + 253)
#define emac (meb.c + 258)
static int pl_o = 20;
