	strcpy(fmt,fmt_o);
	*fmtt = 3;
	*act = 0;
	strcpy(args,args_o);
	*argst = 3;
	*stch1 = stch1_o;
	*stch2 = stch2_o;
	*stcht = 8;
	*srcn = 0;
	strcpy(fname,StdinFile());
	*fnamet = 3;
	*gs = gs_o;
	*gst = 8;
	*scstrt = 3;
	*eofw = eofw_o;
	*eofwt = 8;
	parse_(&cmnd_.gstr,sct_,scb.c);
	strcpy(fmt_o,fmt);
	strcpy(args_o,args);
	stch1_o = *stch1;
	stch2_o = *stch2;
	gs_o = *gs;
	eofw_o = *eofw;
