	*act = 0;
	strcpy(dtermstr,dtermstr_o);
	*dtermstrt = 3;
	*cc = bxCol;
	*cct = 8;
	*cr = bxRow;
	*crt = 8;
	*nc = nc_o;
	*nct = 8;
	*nr = nr_o;
	*nrt = 8;
	*xs = xSquish;
	*xst = 16;
	*ys = ySquish;
	*yst = 16;
	strcpy(ti,ti_o);
	*tit = 3;
	*hpos = hpos_o;
	*hpost = 16;
	*vpos = vpos_o;
	*vpost = 16;
	*hpost = 16;
	*vpost = 16;
	*hpost = 16;
	*vpost = 16;
	*mrkn = mrkn_o;
	*mrknt = 8;
	*hpost = 16;
	*vpost = 16;
	*fight = 16;
	*figwt = 16;
	*fillt = 8;
	*lnt = lnt_o;
	*lntt = 8;
	parse_(&cmnd_.gstr,gmt_,gmb.c);
	strcpy(dtermstr_o,dtermstr);
	bxCol = *cc;
	bxRow = *cr;
	nc_o = *nc;
	nr_o = *nr;
	xSquish = *xs;
	ySquish = *ys;
	strcpy(ti_o,ti);
	hpos_o = *hpos;
	vpos_o = *vpos;
	mrkn_o = *mrkn;
	lnt_o = *lnt;
