/* This file is automatically generated on Wed Jan 17 17:15:21 EST 2001. Do not edit.*/
/* HISTORY is 1 if compiling with comb history mechanism ON
 *            0 otherwise
 *            default is ON
 */
#define HISTORY 1
