	strcpy(ff,ff_o);
	*fft = 3;
	*act = 0;
	*imn = imn_o;
	*imnt = 8;
	*stn = stn_o;
	*stnt = 8;
	strcpy(obj,"");
	*objt = 3;
	strcpy(tel,"");
	*telt = 3;
	*revyt = 8;
	*dmin = DRAGON;
	*dmint = 16;
	*dmax = DRAGON;
	*dmaxt = 16;
	*bitpx = bitpx_o;
	*bitpxt = 8;
	*blnkt = 16;
	parse_(&cmnd_.gstr,wft_,wfb.c);
	strcpy(ff_o,ff);
	imn_o = *imn;
	stn_o = *stn;
	bitpx_o = *bitpx;
