	*snt = 4;
	*istep = 1;
	*istept = 8;
	*fsst = 8;
	*firstt = 8;
	*lastt = 8;
	*lmttyp = 0;
	*lbetyp = 0;
	*lbknd = scan_.mbknd;
	*lbkndt = 8;
	*ssn = ssn_o;
	*ssnt = 8;
	*typet = 3;
	*tsflt = 8;
	*tflgt = 8;
	*pflt = 8;
	parse_(&cmnd_.gstr,gtt_,gtb.c);
	ssn_o = *ssn;
