	*apf = main_.apfl;
	*apft = 8;
	*ucl = labelsUC;
	*uclt = 8;
	strcpy(sp,main_.stkpth);
	*spt = 3;
	*proj = 0;
	*htyp = 0;
	*ywf = main_.warny;
	*ywft = 8;
	*msg = main_.drgmes;
	*msgt = 8;
	*nosho = noShow;
	*noshot = 8;
	parse_(&cmnd_.gstr,opt_,opb.c);
	main_.apfl = *apf;
	labelsUC = *ucl;
	strcpy(main_.stkpth,sp);
	main_.warny = *ywf;
	main_.drgmes = *msg;
	noShow = *nosho;
